---

- name: Install collectd
  apt: name=collectd state=present

- include: nginx.yaml
  when: collectd_plugin_nginx

- name: Copy collectd config
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf
  notify:
    - restart collectd
