---

- name: Install Nginx
  apt: name=nginx state=present

- name: Copy mime.types
  template: src=mime.types.j2 dest=/etc/nginx/mime.types.h5bp
  notify:
   - test and reload Nginx

- name: Copy base config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    validate="nginx -t -c %s"
  notify:
   - test and reload Nginx

- name: Copy shared SSL config directives
  template: src=ssl.conf.j2 dest=/etc/nginx/ssl.conf
  notify:
   - test and reload Nginx

- name: Generate a strong Diffie-Hellman group
  command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
    creates=/etc/nginx/dhparams.pem
  notify: test and reload Nginx

- name: Ensure appropriate DH group file ownership/permissions
  file: path=/etc/nginx/dhparams.pem owner=root group=root mode=0640 state=file
  notify: test and reload Nginx

- name: Copy default Nginx site config
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
   - test and reload Nginx

- name: Activate default Nginx site config
  file:
    state: link
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
  notify:
   - test and reload Nginx
